import BestDeals from "@/components/BestDeals";
import Hero from "@/components/Hero";
import NewArrival from "@/components/NewArrival";
import Head from "next/head";

export default function Home({ categories, products }) {
  return (
    <>
      <Head>
        <title>Win Store | Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Hero categories={categories} />
        <NewArrival products={products} />
        <BestDeals categories={categories} products={products} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://fakestoreapi.com/products/categories");
  const categories = await res.json();

  const response = await fetch("https://fakestoreapi.com/products");
  const products = await response.json();

  return {
    props: {
      categories,
      products,
    },
    revalidate: 60,
  };
};
