import BestDeals from "@/components/BestDeals";
import Hero from "@/components/Hero";
import NewArrival from "@/components/NewArrival";
import axios from "axios";
import Head from "next/head";

export default function Home({ categories, products }) {
  return (
    <>
      <Head>
        <title>Win Store | Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Hero categories={categories} />
        <NewArrival products={products} />
        <BestDeals categories={categories} products={products} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  // Get All Categories
  const { data: categories } = await axios.get(
    "https://fakestoreapi.com/products/categories"
  );

  // Get All Products
  const { data: products } = await axios.get(
    "https://fakestoreapi.com/products"
  );

  return {
    props: {
      categories,
      products,
    },
    revalidate: 60,
  };
};
